### ISSUE TITLE
copyAndReplace strips AngularJS tags, option to change delimiter?

### ISSUE THREAD

**Issue by owen-soak** [soufyakoub/mix-replacer#3]
In my index.html i'm using doubloe braces for AngularJS to modify a class on the body, as this plugin uses the same syntax its stripping this from the index.html file as i move it to the dist dir.

Suggestion: Optional param / config option to change this to something different

**Comment by recursive-beast** [comment]
Hello @owen-soak ,

I'll start working on it right now.

**Comment by recursive-beast** [comment]
@owen-soak , update with npm and refer to this [section][readme_options] from the README.

[readme_options]: https://github.com/soufyakoub/mix-replacer#options

**Comment by owex** [comment]
@soufyakoub Great work!

**Comment by recursive-beast** [comment]
@owex Thank you.
